service: lambda-prueba
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    shouldStartNameWithService: true
functions:
  metodoInicial:
    handler: handler.metodoInicial
    events:
      - http:
          path: /prueba/prueba1
          method: get